export { default as Banner } from './Banner.vue'
export { default as GoogleSignIn } from './GoogleSignIn.vue'
export { default as SpinnerLoader } from './SpinnerLoader.vue'
export { default as LogoCloud } from './LogoCloud.vue' 
export { default as Ripple } from './Ripple.vue'
export { default as CookieConsent } from './CookieConsent.vue'